### ISSUE TITLE
Enhance standings to include goal differential and cards

### ISSUE THREAD

**Issue by chadmack** [Haacked/TournamentMaker#32]
See mockup:
![github_tcc](https://cloud.githubusercontent.com/assets/5216350/17232939/b400f6a0-54e0-11e6-98bc-3f9c8c6b7f88.png)

Update values in standings so that teams can better track their progress against the tiebreaker rules.

Tiebreaker Rules

a.   Head-to-head results, if any;
b.   Goal difference up to three;
c. 	Most goals scored across qualifying matches;
a. No more than three possible goals per match, calculated by the final scoreline (e.g., 3-0, 7-2,
8-3).
b. No more than nine goals across three qualifying matches.
d.   Least goals scored against;
e.   Least amount of yellow and red cards;
f. 	A coin toss

**Comment by Haacked** [comment]
I implemented everything but  the tie breaker rules. I'll move those to another issue.
