### ISSUE TITLE
Add a different scoring values option for tournaments

### ISSUE THREAD

**Issue by chadmack** [Haacked/TournamentMaker#33]
There are two main scoring values that are used for tournaments. It would be cool to have the option to select which type of scoring we want per tournament. This allows for greater disparity between the scoring and avoids having to employ tiebreakers - particularly in a tournament without brackets.

3 pts - win
1 pt - draw
0 pt - loss

OR

A maximum of ten points may be awarded for each game. The following point system shall be followed:    

-Six points for a victory.  
Three points for a draw.  
One point for each goal scored, up to a maximum of 3 points per game.  
One point for a shut-out.  

Group play draw (tie) point calculation examples:       

a) 0-0 tie will be scored as four points for each team (3 points for the draw and 1 point  for the shut-out).     
b) a 1 -1tie will be scored as four points for each team (3 points for the draw and 1 point  for the goal).     
c) a 2-2 tie will be scored as five points for reach team (3 points for the draw and 2  points for the two goals).        
d) a 3-3 tie will be scored as six points for each team (3 points for the draw and 3 points  for the three goals).   
e) 4-4, 5-5, 6-6, etc. will also be scored as six points for each team (3 points  for the draw and a maximum of 1point for each goals scored up to a maximum of three  points per game).

**Comment by Haacked** [comment]
I implemented this. Just edit a tournament to change the scoring rules and the standings will be updated immediately. I made the default rule for new tournaments to be 3pts for win and 1pt for draw, but you can edit any tournament and change the rules and see how it affects the standings.
