### ISSUE TITLE
Error when adding a new team/group to the 2017 tournaments

### ISSUE THREAD

**Issue by chadmack** [Haacked/TournamentMaker#42]
Error screenshot attached. 

[GitHub_Error1.pdf](https://github.com/Haacked/TournamentMaker/files/1149573/GitHub_Error1.pdf)

**Comment by Haacked** [comment]
@chadmack instead of sending a PDF, could you select and copy and paste the error text? Important info was truncated in the PDF. Thanks!

**Comment by Haacked** [comment]
I was able to reproduce the problem. I'll fix it. :smile:

**Comment by Haacked** [comment]
@chadmack could you try it again? I deployed a fix but I forgot the username and password to get in.
