### ISSUE TITLE
Ability to edit tournament description field

### ISSUE THREAD

**Issue by chadmack** [Haacked/TournamentMaker#6]
This would be really helpful so that I can go back after creating a tourney and change the description to include the names of the winners...a common question that I get from companies who have recently joined the competition or want a historical look into who has won.

![tourney-description](https://cloud.githubusercontent.com/assets/5216350/3812625/0ac8f6fa-1cac-11e4-828e-341decafeb12.gif)

**Comment by Haacked** [comment]
@chadmack I think I fixed this a long time ago.
